// ────────────────────────────────────────────────────────────────────────────
//  myOrgTracker – Send Email Hook (Brevo)
// ────────────────────────────────────────────────────────────────────────────
//  Receives Supabase's Send Email Hook payload, builds a branded HTML email,
//  and ships it via the Brevo transactional email API.
//
//  Required environment secrets (set in Supabase → Edge Functions → Secrets):
//    BREVO_API_KEY            xkeysib-... (your Brevo v3 API key)
//    SEND_EMAIL_HOOK_SECRET   v1,whsec_... (generated by the Auth Hook when you create it)
//    FROM_EMAIL               noreply@yourdomain.com (a verified Brevo sender)
//    FROM_NAME                myOrgTracker (display name)
// ────────────────────────────────────────────────────────────────────────────

import { Webhook } from "https://esm.sh/standardwebhooks@1.0.0";

const BREVO_API_KEY = Deno.env.get("BREVO_API_KEY") ?? "";
const FROM_EMAIL    = Deno.env.get("FROM_EMAIL")    ?? "";
const FROM_NAME     = Deno.env.get("FROM_NAME")     ?? "myOrgTracker";
const HOOK_SECRET_RAW = Deno.env.get("SEND_EMAIL_HOOK_SECRET") ?? "";
// The standardwebhooks library wants the raw base64 secret without the "v1,whsec_" prefix.
const HOOK_SECRET = HOOK_SECRET_RAW.replace(/^v1,whsec_/, "");
// Supabase auto-injects this into the Edge Function runtime — we use it to authorize
// the verify URL we paste into emails (otherwise the endpoint returns
// "No API key found in request" when the user clicks the link).
const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY") ?? "";

// ────────────────────────────────────────────────────────────────────────────
//  Brand tokens (mirror the in-app palette)
// ────────────────────────────────────────────────────────────────────────────
const BG      = "#f4ede1";
const SURFACE = "#fbf6ec";
const INK     = "#18181b";
const INK2    = "#5d5a52";
const INK3    = "#7a7568";
const INK4    = "#a89f8d";
const BORDER  = "rgba(61,46,31,0.06)";
const BORDER2 = "rgba(61,46,31,0.08)";

const SERIF = "'EB Garamond',Georgia,'Times New Roman',serif";
const SANS  = "'Geist',-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif";
const MONO  = "'DM Mono',Menlo,Consolas,monospace";

// ────────────────────────────────────────────────────────────────────────────
//  Per-email content. Add a key here for any new email_action_type Supabase
//  might throw at us; default falls back to magiclink.
// ────────────────────────────────────────────────────────────────────────────
type Action = {
  subject:   string;
  preheader: string;
  eyebrow:   string;
  heading:   string;
  intro:     string;
  ctaLabel:  string;
  fineprint: string;
};

const ACTIONS: Record<string, Action> = {
  // Send Login Setup / Resend Login Link from the admin app, or any
  // signInWithOtp() call from the front end.
  magiclink: {
    subject:   "Your sign-in link for myOrgTracker",
    preheader: "Your sign-in link for myOrgTracker. Expires in one hour.",
    eyebrow:   "Sign-in link",
    heading:   "<em style=\"font-style:italic;\">Open your tracker.</em>",
    intro:     "Click the button below to sign in to myOrgTracker. If this is your first time, you'll be guided through choosing a password — once that's set you can sign in with email and password from then on.",
    ctaLabel:  "Open myOrgTracker  →",
    fineprint: "This link expires in one hour and can only be used once. If you didn't request it, you can safely ignore this email.",
  },

  // "Forgot password?" on the sign-in page.
  recovery: {
    subject:   "Reset your myOrgTracker password",
    preheader: "Reset your myOrgTracker password. Expires in one hour.",
    eyebrow:   "Password reset",
    heading:   "<em style=\"font-style:italic;\">Reset your password.</em>",
    intro:     "We received a request to reset the password for your myOrgTracker account. Click the button below to set a new one.",
    ctaLabel:  "Set a new password  →",
    fineprint: "This link expires in one hour. If you didn't request a password reset, you can safely ignore this email — your account stays as it is.",
  },

  // Direct signup (only fires if email confirmation is turned on in Supabase).
  signup: {
    subject:   "Confirm your email for myOrgTracker",
    preheader: "Confirm your email to activate your myOrgTracker account.",
    eyebrow:   "Confirm your email",
    heading:   "<em style=\"font-style:italic;\">One more step.</em>",
    intro:     "Welcome to myOrgTracker. Tap the button below to confirm this email address and finish setting up your account.",
    ctaLabel:  "Confirm my email  →",
    fineprint: "If you didn't create a myOrgTracker account, ignore this email and the request will expire on its own.",
  },

  // Supabase admin-API invite (admin.inviteUserByEmail).
  invite: {
    subject:   "You're invited to myOrgTracker",
    preheader: "You've been invited to myOrgTracker.",
    eyebrow:   "You're invited",
    heading:   "<em style=\"font-style:italic;\">You're in.</em>",
    intro:     "Your team has set up a myOrgTracker account for you. Click the button below to accept the invite and choose a password — that's all the setup you need.",
    ctaLabel:  "Accept invite  →",
    fineprint: "If you weren't expecting this, you can safely ignore the email — the invite will quietly expire.",
  },

  // User changes their own email (Secure Email Change OFF: one email goes to
  // the new address. Secure Email Change ON: this is the new-address email.)
  email_change: {
    subject:   "Confirm your new email for myOrgTracker",
    preheader: "Confirm your new email address for myOrgTracker.",
    eyebrow:   "Confirm new email",
    heading:   "<em style=\"font-style:italic;\">Confirm the change.</em>",
    intro:     "You requested to change the email on your myOrgTracker account to this address. Click the button below to confirm — once you do, this becomes your new sign-in email.",
    ctaLabel:  "Confirm new email  →",
    fineprint: "If you didn't request this change, ignore this email and contact your admin so they can lock down the account.",
  },

  // Secure Email Change ON: this email goes to the OLD address as a heads-up.
  // (Supabase calls this email_action_type "email_change_new" — the naming is
  // legacy/confusing; see the Supabase docs.)
  email_change_new: {
    subject:   "Confirm an email change on your myOrgTracker account",
    preheader: "Confirm the email change on your myOrgTracker account.",
    eyebrow:   "Confirm email change",
    heading:   "<em style=\"font-style:italic;\">Confirm it's you.</em>",
    intro:     "Someone requested to change the email on this myOrgTracker account. Confirm below if it was you.",
    ctaLabel:  "Confirm change  →",
    fineprint: "If you didn't request this, do NOT click the button — contact your admin immediately. The change won't go through unless both this email and the new address confirm.",
  },

  // Rare — only fires if you turn on MFA reauth for sensitive actions.
  reauthentication: {
    subject:   "Confirm your action on myOrgTracker",
    preheader: "Confirm your action on myOrgTracker.",
    eyebrow:   "Confirm action",
    heading:   "<em style=\"font-style:italic;\">Confirm it's you.</em>",
    intro:     "Use the button below to confirm a sensitive action on your myOrgTracker account.",
    ctaLabel:  "Confirm  →",
    fineprint: "If you didn't initiate this action, ignore this email and the request will expire — but consider changing your password.",
  },
};

// ────────────────────────────────────────────────────────────────────────────
//  HTML template — bulletproof email scaffold (table-based, MSO-safe)
// ────────────────────────────────────────────────────────────────────────────
function buildEmailHtml(opts: {
  preheader: string;
  eyebrow:   string;
  heading:   string;
  intro:     string;
  ctaLabel:  string;
  url:       string;
  fineprint: string;
}): string {
  return `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="x-apple-disable-message-reformatting">
<meta name="color-scheme" content="light only">
<meta name="supported-color-schemes" content="light">
<title>myOrgTracker</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&family=Geist:wght@400;500&family=DM+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
  body { margin:0 !important; padding:0 !important; width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; }
  table { border-collapse:collapse !important; mso-table-lspace:0pt; mso-table-rspace:0pt; }
  img { border:0; line-height:100%; outline:none; text-decoration:none; -ms-interpolation-mode:bicubic; }
  a { color:${INK}; }
  @media only screen and (max-width:480px) {
    .container { width:100% !important; max-width:100% !important; }
    .px { padding-left:24px !important; padding-right:24px !important; }
    .cta a, .cta v\\:roundrect { width:100% !important; max-width:100% !important; }
    h1.hero { font-size:26px !important; }
  }
  [data-ogsc] body, [data-ogsb] body { background-color:${BG} !important; }
</style>
</head>
<body style="margin:0;padding:0;background-color:${BG};font-family:${SANS};color:${INK};">

<div style="display:none;font-size:1px;color:${BG};line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;">
  ${opts.preheader}
</div>

<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:${BG};">
  <tr>
    <td align="center" style="padding:48px 16px;">

      <table role="presentation" cellpadding="0" cellspacing="0" border="0" class="container" width="440" style="max-width:440px;">
        <tr>
          <td align="center" style="padding-bottom:36px;">
            <span style="font-family:${SERIF};font-size:26px;line-height:1;letter-spacing:-0.015em;color:${INK};">
              <span style="font-style:italic;font-weight:400;">my</span><span style="font-weight:600;">Org</span><span style="font-weight:400;color:${INK3};">Tracker</span>
            </span>
          </td>
        </tr>
      </table>

      <table role="presentation" cellpadding="0" cellspacing="0" border="0" class="container" width="440" style="max-width:440px;background-color:${SURFACE};border-radius:20px;border:1px solid ${BORDER};">
        <tr>
          <td class="px" style="padding:32px 32px 28px 32px;">

            <p style="margin:0 0 14px 0;font-family:${MONO};font-size:10px;font-weight:500;letter-spacing:0.18em;text-transform:uppercase;color:${INK4};">
              ${opts.eyebrow}
            </p>

            <h1 class="hero" style="margin:0 0 14px 0;font-family:${SERIF};font-weight:400;font-size:30px;letter-spacing:-0.01em;line-height:1.15;color:${INK};">
              ${opts.heading}
            </h1>

            <p style="margin:0 0 24px 0;font-family:${SANS};font-size:15px;line-height:1.6;color:${INK2};">
              ${opts.intro}
            </p>

            <table role="presentation" class="cta" cellpadding="0" cellspacing="0" border="0" width="100%">
              <tr>
                <td align="center" style="padding:6px 0 4px 0;">
                  <!--[if mso]>
                  <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="${opts.url}" style="height:52px;v-text-anchor:middle;width:376px;" arcsize="22%" stroke="f" fillcolor="${INK}">
                    <w:anchorlock/>
                    <center style="color:#fafaf8;font-family:Arial,sans-serif;font-size:15px;font-weight:500;">${opts.ctaLabel}</center>
                  </v:roundrect>
                  <![endif]-->
                  <!--[if !mso]><!-- -->
                  <a href="${opts.url}" style="display:inline-block;background-color:${INK};color:#fafaf8;text-decoration:none;border-radius:11px;padding:0 32px;height:52px;line-height:52px;font-family:${SANS};font-size:15px;font-weight:500;letter-spacing:0.005em;width:auto;min-width:280px;text-align:center;">${opts.ctaLabel}</a>
                  <!--<![endif]-->
                </td>
              </tr>
            </table>

            <p style="margin:22px 0 4px 0;font-family:${SANS};font-size:13px;line-height:1.55;color:${INK3};">
              Or paste this link into your browser:
            </p>
            <p style="margin:0;font-family:${MONO};font-size:11px;line-height:1.45;color:${INK4};word-break:break-all;">
              <a href="${opts.url}" style="color:${INK};text-decoration:underline;">${opts.url}</a>
            </p>

            <hr style="margin:24px 0 16px 0;border:none;border-top:1px solid ${BORDER2};">

            <p style="margin:0;font-family:${SANS};font-size:12px;line-height:1.6;color:${INK4};">
              ${opts.fineprint}
            </p>

          </td>
        </tr>
      </table>

      <table role="presentation" cellpadding="0" cellspacing="0" border="0" class="container" width="440" style="max-width:440px;">
        <tr>
          <td align="center" style="padding:28px 0 0 0;">
            <p style="margin:0;font-family:${MONO};font-size:11px;letter-spacing:0.14em;text-transform:uppercase;color:${INK4};">
              myorgtracker
            </p>
          </td>
        </tr>
      </table>

    </td>
  </tr>
</table>
</body>
</html>`;
}

// ────────────────────────────────────────────────────────────────────────────
//  Plain-text fallback (some recipients prefer or only get text)
// ────────────────────────────────────────────────────────────────────────────
function buildEmailText(opts: { intro: string; ctaLabel: string; url: string; fineprint: string; }): string {
  return `myOrgTracker

${opts.intro}

${opts.ctaLabel.replace(/\s*→\s*$/, "")}: ${opts.url}

${opts.fineprint}

— myOrgTracker
`;
}

// ────────────────────────────────────────────────────────────────────────────
//  Build Supabase verify URL from the hook payload.
//  The verify endpoint redirects the user (after consuming the token) to
//  email_data.redirect_to with whatever flow params Supabase needs.
//
//  IMPORTANT: /auth/v1/verify requires an `apikey` — usually sent as a header
//  by the JS SDK, but a clicked email link can't send headers. So we attach
//  it as a query param. (Supabase's own Resend example omits this and breaks
//  with "No API key found in request" when users click the link.)
// ────────────────────────────────────────────────────────────────────────────
function buildVerifyUrl(siteUrl: string, tokenHash: string, type: string, redirectTo: string): string {
  // email_data.site_url arrives as "https://PROJECT.supabase.co/auth/v1"
  // Strip everything from /auth onward so we don't double the path.
  const base = siteUrl.replace(/\/auth.*$/, "");

  // Normalize the app redirect so we ALWAYS land on /signup regardless of how
  // the caller passed redirect_to:
  //   "https://app.example.com"          → "https://app.example.com/signup"
  //   "https://app.example.com/"         → "https://app.example.com/signup"
  //   "https://app.example.com/signup"   → "https://app.example.com/signup"  (unchanged — was double-appending before)
  //   "https://app.example.com/signup/"  → "https://app.example.com/signup"
  const trimmed = redirectTo.replace(/\/+$/, "");
  const appRedirect = /\/signup$/.test(trimmed) ? trimmed : trimmed + "/signup";

  const params = new URLSearchParams({
    token: tokenHash,
    type,
    redirect_to: appRedirect,
    apikey: SUPABASE_ANON_KEY,
  });
  return `${base}/auth/v1/verify?${params.toString()}`;
}

// ────────────────────────────────────────────────────────────────────────────
//  Brevo send
// ────────────────────────────────────────────────────────────────────────────
async function sendViaBrevo(to: string, subject: string, html: string, text: string): Promise<void> {
  if (!BREVO_API_KEY) throw new Error("BREVO_API_KEY env var is not set");
  if (!FROM_EMAIL)    throw new Error("FROM_EMAIL env var is not set");

  const res = await fetch("https://api.brevo.com/v3/smtp/email", {
    method: "POST",
    headers: {
      "api-key": BREVO_API_KEY,
      "Content-Type": "application/json",
      "Accept": "application/json",
    },
    body: JSON.stringify({
      sender:      { name: FROM_NAME, email: FROM_EMAIL },
      to:          [{ email: to }],
      subject,
      htmlContent: html,
      textContent: text,
    }),
  });

  if (!res.ok) {
    const errBody = await res.text();
    throw new Error(`Brevo API ${res.status}: ${errBody}`);
  }
}

// ────────────────────────────────────────────────────────────────────────────
//  Webhook handler
// ────────────────────────────────────────────────────────────────────────────
Deno.serve(async (req) => {
  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  const rawPayload = await req.text();
  const headers    = Object.fromEntries(req.headers);

  // 1. Verify the Supabase webhook signature so randos can't trigger sends
  let verified: unknown;
  try {
    if (!HOOK_SECRET) throw new Error("SEND_EMAIL_HOOK_SECRET env var is not set");
    const wh = new Webhook(HOOK_SECRET);
    verified = wh.verify(rawPayload, headers);
  } catch (e) {
    return new Response(JSON.stringify({
      error: { http_code: 401, message: `Webhook signature invalid: ${(e as Error).message}` }
    }), { status: 401, headers: { "content-type": "application/json" } });
  }

  const { user, email_data } = verified as {
    user: { email: string; new_email?: string };
    email_data: {
      token:           string;
      token_hash:      string;
      token_new?:      string;
      token_hash_new?: string;
      redirect_to:     string;
      email_action_type: string;
      site_url:        string;
    };
  };

  // 2. Pick the right content for this action; fall back to magiclink for anything weird
  const action = ACTIONS[email_data.email_action_type] ?? ACTIONS.magiclink;

  // 3. Pick the right token_hash.
  //    For "email_change_new" (sent to the OLD email when Secure Email Change is on),
  //    Supabase reverses the field naming for backwards-compat reasons:
  //    that recipient needs token_hash_new, NOT token_hash.
  //    Everything else uses the standard token_hash.
  const tokenHash = email_data.email_action_type === "email_change_new"
    ? (email_data.token_hash_new ?? email_data.token_hash)
    : email_data.token_hash;

  // 4. Pick the right recipient. Same special-case: old email for email_change_new.
  const recipient = email_data.email_action_type === "email_change_new"
    ? user.email
    : (user.new_email ?? user.email);

  // 5. Build the verify URL Supabase expects
  const verifyUrl = buildVerifyUrl(
    email_data.site_url,
    tokenHash,
    email_data.email_action_type,
    email_data.redirect_to,
  );

  // 6. Build HTML + text bodies and ship
  const html = buildEmailHtml({
    preheader: action.preheader,
    eyebrow:   action.eyebrow,
    heading:   action.heading,
    intro:     action.intro,
    ctaLabel:  action.ctaLabel,
    url:       verifyUrl,
    fineprint: action.fineprint,
  });
  const text = buildEmailText({
    intro:     action.intro,
    ctaLabel:  action.ctaLabel,
    url:       verifyUrl,
    fineprint: action.fineprint,
  });

  try {
    await sendViaBrevo(recipient, action.subject, html, text);
  } catch (e) {
    console.error("Brevo send failed:", e);
    return new Response(JSON.stringify({
      error: { http_code: 500, message: `Email send failed: ${(e as Error).message}` }
    }), { status: 500, headers: { "content-type": "application/json" } });
  }

  // 7. Supabase wants 200 + empty body on success
  return new Response("{}", { status: 200, headers: { "content-type": "application/json" } });
});
